#!/bin/bash
echo "Activating Temp Logger"
FILE="temp_log.txt"
head="Time,temp"
echo $head > $FILE

T=$"C"
if [[ $1 == "-f" || $1 == "-F" ]]; then
	T=$"f"
fi 
LASTTIME=$(python -c "import time; print(int(time.time()))")
read -p "<enter> to take data"
while true; do
	TIME=$(python -c "import time; print(int(time.time()))")
	if [[ $((TIME-LASTTIME)) -ge .1 ]]; then
		#echo 'Monitoring Temperature'
		#Monitor Time & Temp with python
		text=$(python tempmonitor.py "$T")
		printf "$text\n" >> $FILE1
		LASTTIME=$TIME
	fi
done
